### ISSUE TITLE
Use a working license instead of UNLICENSE

### ISSUE THREAD

**Issue by Valloric** [docopt/docopt.rs#1]
[I posted this in your Reddit thread, but it should be an actual issue.]

Please don't use UNLICENSE for your license. [It doesn't actually work](http://projects.opensource.org/pipermail/license-review/2012-January/000052.html). All uses of UNLICENSE can be replaced with uses of the [Apache 2 license](http://www.apache.org/licenses/LICENSE-2.0.html) (which actually works); you get the same "do whatever you want with it" support without causing your users pain because your license makes no legal sense.

Apache 2 really is what you want; unlike the MIT license, it covers the following as well:
- Any patches you receive are also licensed under Apache 2. MIT says nothing on this and thus leaves any project using it in a weird state after merging in external contributions.
- It gives a patent license as well. 
- Other minor useful tidbits.

I've made the mistake of using UNLICENSE myself before; learn from my experience.

**Comment by rickmoen** [comment]
Hi, Andrew.  If you are willing to consider an alternative, Rob Landley created for the toybox project the '0BSD' license (Zero-Clause BSD License) by removing a requirements clause from 2-clause BSD, and resulting in text running about ten lines.  Moreover, it's already an <a href="https://opensource.org/licenses/FPL-1.0.0">OSI Certified licence</a>, albeit OSI hasn't yet cleared up some lingering name confusion.

Several years on, my (referenced) damning legal critique of Unlicense on the license-review mailing list still looks to me, IMO, fully merited, but I absolutely applaud your wish to use a copyfree licence.  Maybe 0BSD will be your cuppa.  (copyfree.org lists it as 'Toybox License'.  As I said, there's a lingering name issue being cleared up:  Rob is working on getting everyone to standardise on 0BSD as the short name, and Zero-Clause BSD License as the full name.)

-- Rick Moen
rick@linuxmafia.com

**Comment by BurntSushi** [comment]
> Hi, Andrew. If you are willing to consider an alternative, Rob Landley created
> for the toybox project the '0BSD' license (Zero-Clause BSD License) by removing
> a requirements clause from 2-clause BSD, and resulting in text running about
> ten lines. Moreover, it's already an OSI Certified licence, albeit OSI hasn't
> yet cleared up some lingering name confusion.
> 
> Several years on, my (referenced) damning legal critique of Unlicense on the
> license-review mailing list still looks to me, IMO, fully merited, but I
> absolutely applaud your wish to use a copyfree licence. Maybe 0BSD will be
> your cuppa. (copyfree.org lists it as 'Toybox License'. As I said, there's a
> lingering name issue being cleared up: Rob is working on getting everyone to
> standardise on 0BSD as the short name, and Zero-Clause BSD License as the full
> name.)
> 
> -- Rick Moen
> rick@linuxmafia.com

@rickmoen Thanks for responding, but based on your mailing list posts from 2012, and assuming your perspective hasn't changed, then it's clear to me that we're coming at this from very different angles. The fundamental crux at which we disagree is captured fairly succinctly in this part of your correspondence:

> And that's the pity of it:  Using a very simple standard permissive
> licence such as MIT/X11 License or even a peculiar and cramped but
> somewhat standard 3-line licence like Fair Licence achieves everything
> Bendiken and others want (_and_ actually escape warranty liability)
> except for the ideological point about getting 'out of the copyright
> game'.
>
> And because of that ideological hobbyhorse, everyone's time gets wasted.

Given that, and given the clear condescension expressed towards the type of perspective I hold here, I'm not sure it's particularly productive to discuss this further.

Moreover, about 3 years ago, I [dual licensed this project under the MIT and the UNLICENSE](https://github.com/docopt/docopt.rs/commit/11b5ff3d3939b7d4ba0e09e457f802a37bb5c5dc), which should assuage the practical concerns others have made. I did the same for most of my other projects, and since then, plenty of folks---including large corporations with huge legal infrastructure devoted to figuring out which software licenses are acceptable for them to use---have had no problem using my code.

I've elaborated a bit on my licensing choice in a different project of mine here: https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#license

**Comment by rickmoen** [comment]
Andrew, I'm glad to clarify (and repeat) that I have nothing but respect for your and others' desire to achieve maximally permissive & terse software licensing.  I'm totally sincere about that, and have consistently so said in public and private.  

My sharp criticism (call it condescension if you wish) has been restricted to ignominious failures to address that need, that fail for lack of attention to legal basics, such as <a href="http://linuxmafia.com/faq/Licensing_and_Law/public-domain.html#wtfpl">WTFPL</a> and <a href="http://linuxmafia.com/faq/Licensing_and_Law/public-domain.html#unlicense">Unlicense</a>.  Those licences' structural defects are both gravely fatal and pretty much not disputed by anyone familiar with basics of software licensing and copyright law -- which, like death and taxes, don't go away merely because one dislikes them.

MIT License is excellent, of course -- and about 13 lines of standard ASCII text.  Hypothetically switching to 0BSD would shrink that to about 10 lines, FWIW.

**Comment by BurntSushi** [comment]
> Andrew, I'm glad to clarify (and repeat) that I have nothing but respect for your and others' desire to achieve maximally permissive & terse software licensing. I'm totally sincere about that, and have consistently so said in public and private.

I get that. But I hope it's also clear that I use the Unlicense for at least partially ideological reasons. It is specifically intended as a protest against monopoly copyright interest. Neither the 0BSD nor the MIT achieve that. To you, this is a waste of time. That's a fair position to take; I don't even disagree with it 100%. I'm not that big on activism. But this is one position I've found I can take without actually giving up much, specifically because of the dual licensing with a widely recognized license (MIT).

The point of me using MIT is to hedge against situations where the Unlicense isn't acceptable for one reason or another (perhaps because some legal professional declared it to be unsuitable). To that end, I don't think there is any better choice, including the 0BSD, simply on grounds of broad appeal alone.

> which, like death and taxes, don't go away merely because one dislikes them.

For what it's worth, this is the kind of condescension that I find really unappealing. Presumably you're hear to convince me of something. If that's your goal, then you're really acting against your interests by talking down to me as if I were some cargo culting idiot. Whether that's your intent or not, _that's how you come across to me._ In particular, I'm well aware that the practice of law has absolutely nothing to do with whether I disagree with it or not. However, sometimes laws (or norms) should change, and the only way for that to happen is for someone to act against the status quo. Therefore, your _descriptive_ argument is completely barking up the wrong tree, because I'm making a _prescriptive_ argument.

Now, maybe there exists a better way to stake my ideological ground. Maybe there should be an Unlicense2 that addresses your concerns. So long as the goal is to disclaim monopoly copyright interest, I'd be happy to support that. But I don't know of any such effort, and I certainly do not want to add yet another license to the fray myself. :-)

**Comment by rickmoen** [comment]
> For what it's worth, this is the kind of condescension that I find really unappealing.

I'm typically Scandinavian-American in the sense of habitually telling perceived truths bluntly.  If you want a salesman or flattery, that's somebody else.  

And no, I'm not trying to convince you of anything.  There's nothing in that for me.  I'm just stating my views because it's on a topic of longtime interest to me, because you kindly permit it, and so others will probably find what I'm saying.

Your ideological position is all very well, and I don't differ with it in any way.  I wish the global copyright regime would get out of our way, too.  But meanwhile, if writing software and not wishing to create nasty future legal pitfalls for downstream users and redistributors, it's IMO wise to use competent licensing for the same reason one sticks to competently assembled and maintained cars when driving rather than driving an incompetently built one as a protest for ideological reasons.

Or, at least, if you do, someone's likely to have a bad day.

**Comment by BurntSushi** [comment]
> it's IMO wise to use competent licensing for the same reason one sticks to competently assembled and maintained cars when driving rather than driving an incompetently built one as a protest for ideological reasons.

That's why I dual license and it's also why I drive a Camry.

> I'm typically Scandinavian-American in the sense of habitually telling perceived truths bluntly. If you want a salesman or flattery, that's somebody else.

If your "perceived truth" is that I think the practice of law depends on whether I dislike it or not, then you very clearly must think of me as a blubbering idiot.

Here's my perceived truth: the absence of condescension is not the same as the presence of salesmanship or flattery.

**Comment by BurntSushi** [comment]
Thanks for explaining that in more detail. I'm generally happy to see copyfree licenses get more press.

With that said, we'll have to agree to disagree on how we perceive the world. You see naiveté, but I see rebellion. Rebellion comes in many shapes and sizes, and for it to succeed, you generally need to sacrifice something. Maybe that comes in the form of real world software using sub-optimal software licenses. I am a terrible activist though; which is why I ultimately caved and dual licensed.

Either way, I really do not think your musings on how stupid some social circles are help your cause here. You have an opportunity to educate folks on license choices, but instead you lace it with invective. It's completely distracting. Be blunt. Be honest. Don't sugar coat it. But don't snub your nose at the people you're trying to educate.

**Comment by rickmoen** [comment]
I'd be obliged if you could point out where, anywhere on this topic, I said or implied that anyone was stupid.  On a fairly lengthly search, I can't find examples.

Nor, actually, would that make any sense in light of what I've been saying:  There's nothing of stupidity implied by choosing unsuitable tools for a task, when one is far outside one's field, but hasn't realised why leveraging the work of domain-knowledge experts is crucial.

The only people I come somewhat close to derogating are Mr. Sam Hocevar, author of WTFPL v.2, whose effort produced a hapless failure for lack of attention to basic detail, and Mr. Joe Brockmeier, who meant well and missed the target but less badly than Sam did.  Even them, I certainly wouldn't call stupid, just tragically inept in a way likely to cause much bigger problems for others than for themselves.  

Along those lines, as to what software stakeholders sacrifice in choosing legally flawed licensing in hopes of making a point, I respect that choice right up to the point where they negligently leave legal pitfalls for downstream code reusers, which IMO is morally suspect.  YMMV.

**Comment by BurntSushi** [comment]
That's enough. I've done my best to express my distaste for how you're choosing to continue this conversation, but it's not working. You keep continuing to spew invective and proffer unsolicited opinions on not only entire social groups, but now you're targeting specific individuals. This goes way beyond spreading the word about copyfree licenses, which I'm totally happy to indulge. From my perspective, your social commentary is inflammatory and a waste of my time to read. Please do not bother me with it again.
