### ISSUE TITLE
docopt! macro can't compile.

### ISSUE THREAD

**Issue by Botev** [docopt/docopt.rs#130]
Copy pasting the example from the docs doesn't compile with the error:
`can't find crate for "docopt_macros"
src/main.rs:2 #![plugin(docopt_macros)]
`
I might just plain stupid, but that's another part of rust which is not well documented - importing macros. Could you please tell me how to do it correctly?

**Comment by BurntSushi** [comment]
It's hard to debug your problem without more info. What's your code look like? What does your Cargo.toml look like? What version of Rust are you using?

A few notes:

1. You should have both `docopt` and `docopt_macros` in your `Cargo.toml`. (Per instructions in `README.md`.)
2. `docopt_macros` only works on Rust nightly because it uses a compiler plugin and compiler plugins are unstable (which means they are not available on Rust beta or Rust stable).

Compiler plugins aren't well documented because they are an unstable feature with direct access to the compiler internals. The best we have in that department are examples (by looking at others' code).

**Comment by Botev** [comment]
I see,ok that makes sense, I missed the part of docopt_macros (from the instructions where it said to include them I thought of it as to include #[macro_use] at the top rather than meaning it is a separate repository). Why github still does not have some form of forum or smth, this issue things is not exactly what you want... but anyway thanks for getting back to me so fast!

**Comment by BurntSushi** [comment]
No problem. I'm not that picky over what the issue tracker is used for, especially with low traffic. In some of my other projects, the issue tracker is effectively a support forum. It's cool.
