### ISSUE TITLE
Does docopt-style API scale to the complex use-cases?

### ISSUE THREAD

**Issue by matklad** [docopt/docopt.rs#261]
:wave: @BurntSushi, the [recent](https://old.reddit.com/r/rust/comments/oopepi/argparsebenchmarksrs_collected_benchmarks_for_arg/) reddit discussion got me thinking about arg parsing again, and I'd like to pick your brain (or anyone else's who notices this issue!) on the docopt-style interfaces. 

Looking [at the benchmark](https://github.com/rust-cli/argparse-benchmarks-rs#results), I like xflags performance: it is comparable to pico-args, *but* also gives you auto-generated help messages and ergonomic parsing of arguments into a struct. As a bonus, OsString/PathBuf just work. 

To be clear, `xflags` is broken by design and shouldn't be used for anything user-facing. However, I think it has a couple of great ideas, and I think that marrying xflags and docopt together might actually give a design for arg parser to rule them all. 

The core insight of xflags is that procedural macros are not, by themselves, heavy. Rather, parsing Rust code with syn is heavy, because parsing Rust is complicated. So xflags uses a non-rust DSL as an input, and a very simple hand-written parser for that. 

Today, xflags uses a rather idiosyncratic DSL as an input. I am wondering if using docopt as the input language will work for "perfect" argument parser. 

Finally, the actual questions:

* If we ignore particular implementations, is the docopt language enough to express all complex CLI options? Can you imagine specifying all of the ripgrep arguments as a single string in docopt format, for example? 
* Is there a standard way to specify meta information (most importantly, types) in docopt grammar? I've found [this](https://github.com/dreamgonfly/type-docopt), I wonder if there's other prior art.
* Are there other "CLI specification languages" besides docopt I should look into?

**Comment by BurntSushi** [comment]
That last time I looked or even thought about Docopt in earnest was years ago unfortunately. So I'll basically just guess at your questions using my intuition, so take my answers with a grain of salt:

* ripgrep actually started life using Docopt, and it started with quite a lot of flags. ripgrep's flags are otherwise not terribly complex. I believe all of them are just either boolean flags or flags that accept a single string/number. And there are no sub-commands. IIRC, there are some expressiveness limitations to Docopt, but I can't remember specific examples.
* Not that I'm aware of. And the Docopt project (not just this crate) is effectively dead as far as I can tell.
* Dunno. I don't know of any.

I will note that one of the problems with Docopt that clap (and things like it) solve reasonably nicely is when you have a bunch of sub-commands that share a lot of flags in common. With things like clap, you can use normal code to compose things arbitrarily. Docopt doesn't really permit that level composition, which is kind of a big bummer.

ripgrep also wants some other things (not yet implemented), like the ability for a user to provide `--include` and `--exclude` flags, and then have ripgrep be able to tell the relative order of each of those flags. That way, you can compose the include/exclude rules in order to form precedence matching. (e.g., "this include rule came after that exclude rule, so the include rule wins," just like gitignore.) Clap actually [added an API](https://docs.rs/clap/2.33.3/clap/struct.ArgMatches.html#method.indices_of) for exactly that use case. It's otherwise not possible, and I believe not possible with Docopt.

**Comment by matklad** [comment]
Thanks for sharing your experience! I now recall that I've actually faced the lack of programmatic composability you mention in cargo, at the time when it still has been using docopt!
